collections:
  limbs:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "limbs"
    values:
      layout: "limb"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag