collections:
  limbs:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "limbs"
    values:
      layout: "limb"
      heading: "PLACEHOLDER"
      subheading: "PLACEHOLDER"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      catergory: "PLACEHOLDER"
      image: "/assets/images/blog/default.jpeg"
      alt: "PLACEHOLDER"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      image: "/assets/images/blog/default.jpeg"
      alt: "PLACEHOLDER"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag